spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: status
              uri: http://localhost:8080
              predicates:
                - Path=/api/v1/flowmanager/**
                - Method=GET,POST
server:
  port: 8081